//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class cn_sharesdk_unity3d_ContentTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(cn.sharesdk.unity3d.ContentType), typeof(System.Object));
		L.RegFunction("New", _Createcn_sharesdk_unity3d_ContentType);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("Auto", 0);
		L.RegConstant("Text", 1);
		L.RegConstant("Image", 2);
		L.RegConstant("Webpage", 4);
		L.RegConstant("Music", 5);
		L.RegConstant("Video", 6);
		L.RegConstant("App", 7);
		L.RegConstant("File", 8);
		L.RegConstant("Emoji", 9);
		L.RegConstant("MiniProgram", 10);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Createcn_sharesdk_unity3d_ContentType(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				cn.sharesdk.unity3d.ContentType obj = new cn.sharesdk.unity3d.ContentType();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: cn.sharesdk.unity3d.ContentType.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

