//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class cn_sharesdk_unity3d_ShareContentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(cn.sharesdk.unity3d.ShareContent), typeof(System.Object));
		L.RegFunction("SetHidePlatforms", SetHidePlatforms);
		L.RegFunction("SetTitle", SetTitle);
		L.RegFunction("SetText", SetText);
		L.RegFunction("SetUrl", SetUrl);
		L.RegFunction("SetImagePath", SetImagePath);
		L.RegFunction("SetImageUrl", SetImageUrl);
		L.RegFunction("SetImageArray", SetImageArray);
		L.RegFunction("SetShareType", SetShareType);
		L.RegFunction("SetTitleUrl", SetTitleUrl);
		L.RegFunction("SetComment", SetComment);
		L.RegFunction("SetSite", SetSite);
		L.RegFunction("SetSiteUrl", SetSiteUrl);
		L.RegFunction("SetAddress", SetAddress);
		L.RegFunction("SetFilePath", SetFilePath);
		L.RegFunction("SetMusicUrl", SetMusicUrl);
		L.RegFunction("SetLatitude", SetLatitude);
		L.RegFunction("SetLongitude", SetLongitude);
		L.RegFunction("SetSource", SetSource);
		L.RegFunction("SetAuthor", SetAuthor);
		L.RegFunction("SetSafetyLevel", SetSafetyLevel);
		L.RegFunction("SetContentType", SetContentType);
		L.RegFunction("SetHidden", SetHidden);
		L.RegFunction("SetIsPublic", SetIsPublic);
		L.RegFunction("SetIsFriend", SetIsFriend);
		L.RegFunction("SetIsFamily", SetIsFamily);
		L.RegFunction("SetFriendsOnly", SetFriendsOnly);
		L.RegFunction("SetGroupID", SetGroupID);
		L.RegFunction("SetAudioPath", SetAudioPath);
		L.RegFunction("SetVideoPath", SetVideoPath);
		L.RegFunction("SetNotebook", SetNotebook);
		L.RegFunction("SetTags", SetTags);
		L.RegFunction("SetPrivateStatus", SetPrivateStatus);
		L.RegFunction("SetObjectID", SetObjectID);
		L.RegFunction("SetAlbumID", SetAlbumID);
		L.RegFunction("SetEmotionPath", SetEmotionPath);
		L.RegFunction("SetExtInfoPath", SetExtInfoPath);
		L.RegFunction("SetSourceFileExtension", SetSourceFileExtension);
		L.RegFunction("SetSourceFilePath", SetSourceFilePath);
		L.RegFunction("SetThumbImageUrl", SetThumbImageUrl);
		L.RegFunction("SetUrlDescription", SetUrlDescription);
		L.RegFunction("SetBoard", SetBoard);
		L.RegFunction("SetMenuX", SetMenuX);
		L.RegFunction("SetMenuY", SetMenuY);
		L.RegFunction("SetVisibility", SetVisibility);
		L.RegFunction("SetBlogName", SetBlogName);
		L.RegFunction("SetRecipients", SetRecipients);
		L.RegFunction("SetCCRecipients", SetCCRecipients);
		L.RegFunction("SetBCCRecipients", SetBCCRecipients);
		L.RegFunction("SetAttachmentPath", SetAttachmentPath);
		L.RegFunction("SetDesc", SetDesc);
		L.RegFunction("SetIsPrivateFromSource", SetIsPrivateFromSource);
		L.RegFunction("SetResolveFinalUrl", SetResolveFinalUrl);
		L.RegFunction("SetFolderId", SetFolderId);
		L.RegFunction("SetTweetID", SetTweetID);
		L.RegFunction("SetToUserID", SetToUserID);
		L.RegFunction("SetPermission", SetPermission);
		L.RegFunction("SetEnableShare", SetEnableShare);
		L.RegFunction("SetImageWidth", SetImageWidth);
		L.RegFunction("SetImageHeight", SetImageHeight);
		L.RegFunction("SetAppButtonTitle", SetAppButtonTitle);
		L.RegFunction("SetAndroidExecParam", SetAndroidExecParam);
		L.RegFunction("SetAndroidMarkParam", SetAndroidMarkParam);
		L.RegFunction("SetIphoneExecParam", SetIphoneExecParam);
		L.RegFunction("SetIphoneMarkParam", SetIphoneMarkParam);
		L.RegFunction("SetIpadExecParam", SetIpadExecParam);
		L.RegFunction("SetIpadMarkParam", SetIpadMarkParam);
		L.RegFunction("SetEnableClientShare", SetEnableClientShare);
		L.RegFunction("SetEnableSinaWeiboAPIShare", SetEnableSinaWeiboAPIShare);
		L.RegFunction("SetEnableAdvancedInterfaceShare", SetEnableAdvancedInterfaceShare);
		L.RegFunction("SetShareContentCustomize", SetShareContentCustomize);
		L.RegFunction("GetShareParamsStr", GetShareParamsStr);
		L.RegFunction("GetShareParams", GetShareParams);
		L.RegFunction("New", _Createcn_sharesdk_unity3d_ShareContent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Createcn_sharesdk_unity3d_ShareContent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				cn.sharesdk.unity3d.ShareContent obj = new cn.sharesdk.unity3d.ShareContent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: cn.sharesdk.unity3d.ShareContent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetHidePlatforms(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			obj.SetHidePlatforms(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTitle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetTitle(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetText(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImagePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetImagePath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImageUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetImageUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImageArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			obj.SetImageArray(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShareType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetShareType(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTitleUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetTitleUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetComment(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetComment(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSite(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSite(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSiteUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSiteUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAddress(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAddress(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFilePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetFilePath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMusicUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetMusicUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLatitude(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetLatitude(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLongitude(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetLongitude(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSource(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAuthor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAuthor(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSafetyLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSafetyLevel(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetContentType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetContentType(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetHidden(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetHidden(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsPublic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsPublic(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsFriend(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsFriend(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsFamily(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsFamily(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFriendsOnly(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetFriendsOnly(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetGroupID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetGroupID(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAudioPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAudioPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetVideoPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetVideoPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetNotebook(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetNotebook(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetTags(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPrivateStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetPrivateStatus(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetObjectID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetObjectID(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAlbumID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAlbumID(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEmotionPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetEmotionPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetExtInfoPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetExtInfoPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSourceFileExtension(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSourceFileExtension(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSourceFilePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSourceFilePath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetThumbImageUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetThumbImageUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUrlDescription(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetUrlDescription(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBoard(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetBoard(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMenuX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetMenuX(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMenuY(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetMenuY(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetVisibility(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetVisibility(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBlogName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetBlogName(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRecipients(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetRecipients(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCCRecipients(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetCCRecipients(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBCCRecipients(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetBCCRecipients(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAttachmentPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAttachmentPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDesc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetDesc(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsPrivateFromSource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsPrivateFromSource(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetResolveFinalUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetResolveFinalUrl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFolderId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetFolderId(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTweetID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetTweetID(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetToUserID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetToUserID(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPermission(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetPermission(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEnableShare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetEnableShare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImageWidth(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetImageWidth(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImageHeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetImageHeight(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAppButtonTitle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAppButtonTitle(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAndroidExecParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			System.Collections.Hashtable arg0 = (System.Collections.Hashtable)ToLua.CheckObject<System.Collections.Hashtable>(L, 2);
			obj.SetAndroidExecParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAndroidMarkParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetAndroidMarkParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIphoneExecParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			System.Collections.Hashtable arg0 = (System.Collections.Hashtable)ToLua.CheckObject<System.Collections.Hashtable>(L, 2);
			obj.SetIphoneExecParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIphoneMarkParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetIphoneMarkParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIpadExecParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			System.Collections.Hashtable arg0 = (System.Collections.Hashtable)ToLua.CheckObject<System.Collections.Hashtable>(L, 2);
			obj.SetIpadExecParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIpadMarkParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetIpadMarkParam(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEnableClientShare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetEnableClientShare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEnableSinaWeiboAPIShare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetEnableSinaWeiboAPIShare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEnableAdvancedInterfaceShare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetEnableAdvancedInterfaceShare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShareContentCustomize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			cn.sharesdk.unity3d.PlatformType arg0 = (cn.sharesdk.unity3d.PlatformType)ToLua.CheckObject(L, 2, typeof(cn.sharesdk.unity3d.PlatformType));
			cn.sharesdk.unity3d.ShareContent arg1 = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 3);
			obj.SetShareContentCustomize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetShareParamsStr(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			string o = obj.GetShareParamsStr();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetShareParams(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			cn.sharesdk.unity3d.ShareContent obj = (cn.sharesdk.unity3d.ShareContent)ToLua.CheckObject<cn.sharesdk.unity3d.ShareContent>(L, 1);
			System.Collections.Hashtable o = obj.GetShareParams();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

