//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CustomCSharpMethodWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("CustomCSharpMethod");
		L.RegFunction("Run", Run);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Run(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			CustomCSharpMethod.Run();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

